[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-prerender-spa"

[plugins.inputs]
  # point plugin to the built site folder
  source = "dist"